config/routes.rb
Rails.application.routes.draw do
  resources :responses
  resources :multiple_choice_options
  resources :questions
  resources :houses
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'questions#index'

  resources :administrators, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :multiple_choice_options
  has_many :responses
  enum format: [:multiple_choice, :short_answer]

  validates :body, presence: true
  validates :answer, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def users
    @users ||= User.all
  end
  helper_method :users

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:body, :answer, :author_id, :format, :date_last_asked)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.select(:author_id, form_selection(users, :slack_handle)) %>
  </div>

<!--  Temporarily making it just short answer for the meantime-->
<!--  <div class="field">-->
    <%#= form.label :format %>
    <%#= form.number_field :format %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Body</th>-->
<!--      <th>Answer</th>-->
<!--      <th>Author</th>-->
<!--      <th>Type</th>-->
<!--      <th>Date last asked</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to "#{question.body}", question %></td>
        <td><%= "by: #{question.author.slack_handle}" %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @question.body %></h1>

<p>
  <strong>Answer:</strong>
  <span class="spoiler"><%= @question.answer %></span>
</p>

<p>
  <strong>Author:</strong>
  <%= link_to "#{@question.author.slack_handle}", user_path(@question.author) %>
</p>

<p>
  <strong>Format:</strong>
  <%= @question.format %>
</p>

<p>
  <strong>Date last asked:</strong>
  <%= @question.date_last_asked || "Never" %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %> |
<%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %>

<h1>Responses</h1>
<% if @question.responses.size > 0 %>
  <table>
    <tbody>
    <% @question.responses.each do |response| %>
      <tr>
        <td><%= response.user.slack_handle %></td>
        <td><%= link_to "#{response.body}", response %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No answers yet.</p>
<% end %>