config/routes.rb
Rails.application.routes.draw do
  resources :responses
  resources :multiple_choice_options
  resources :questions
  resources :houses
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'questions#index'

  resources :administrators, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
end

app/models/multiple_choice_option.rb
class MultipleChoiceOption < ApplicationRecord
  belongs_to :question
end

app/controllers/multiple_choice_options_controller.rb
class MultipleChoiceOptionsController < ApplicationController
  before_action :set_multiple_choice_option, only: [:show, :edit, :update, :destroy]

  # GET /multiple_choice_options
  # GET /multiple_choice_options.json
  def index
    @multiple_choice_options = MultipleChoiceOption.all
  end

  # GET /multiple_choice_options/1
  # GET /multiple_choice_options/1.json
  def show
  end

  # GET /multiple_choice_options/new
  def new
    @multiple_choice_option = MultipleChoiceOption.new
  end

  # GET /multiple_choice_options/1/edit
  def edit
  end

  # POST /multiple_choice_options
  # POST /multiple_choice_options.json
  def create
    @multiple_choice_option = MultipleChoiceOption.new(multiple_choice_option_params)

    respond_to do |format|
      if @multiple_choice_option.save
        format.html { redirect_to @multiple_choice_option, notice: 'Multiple choice option was successfully created.' }
        format.json { render :show, status: :created, location: @multiple_choice_option }
      else
        format.html { render :new }
        format.json { render json: @multiple_choice_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /multiple_choice_options/1
  # PATCH/PUT /multiple_choice_options/1.json
  def update
    respond_to do |format|
      if @multiple_choice_option.update(multiple_choice_option_params)
        format.html { redirect_to @multiple_choice_option, notice: 'Multiple choice option was successfully updated.' }
        format.json { render :show, status: :ok, location: @multiple_choice_option }
      else
        format.html { render :edit }
        format.json { render json: @multiple_choice_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /multiple_choice_options/1
  # DELETE /multiple_choice_options/1.json
  def destroy
    @multiple_choice_option.destroy
    respond_to do |format|
      format.html { redirect_to multiple_choice_options_url, notice: 'Multiple choice option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_multiple_choice_option
      @multiple_choice_option = MultipleChoiceOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def multiple_choice_option_params
      params.require(:multiple_choice_option).permit(:question_id, :option)
    end
end

app/helpers/multiple_choice_options_helper.rb
module MultipleChoiceOptionsHelper
end

app/views/multiple_choice_options/_form.html.erb
<%= form_with(model: multiple_choice_option, local: true) do |form| %>
  <% if multiple_choice_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(multiple_choice_option.errors.count, "error") %> prohibited this multiple_choice_option from being saved:</h2>

      <ul>
        <% multiple_choice_option.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :option %>
    <%= form.text_field :option %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/multiple_choice_options/edit.html.erb
<h1>Editing Multiple Choice Option</h1>

<%= render 'form', multiple_choice_option: @multiple_choice_option %>

<%= link_to 'Show', @multiple_choice_option %> |
<%= link_to 'Back', multiple_choice_options_path %>

app/views/multiple_choice_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Multiple Choice Options</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @multiple_choice_options.each do |multiple_choice_option| %>
      <tr>
        <td><%= multiple_choice_option.question_id %></td>
        <td><%= multiple_choice_option.option %></td>
        <td><%= link_to 'Show', multiple_choice_option %></td>
        <td><%= link_to 'Edit', edit_multiple_choice_option_path(multiple_choice_option) %></td>
        <td><%= link_to 'Destroy', multiple_choice_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Multiple Choice Option', new_multiple_choice_option_path %>

app/views/multiple_choice_options/new.html.erb
<h1>New Multiple Choice Option</h1>

<%= render 'form', multiple_choice_option: @multiple_choice_option %>

<%= link_to 'Back', multiple_choice_options_path %>

app/views/multiple_choice_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @multiple_choice_option.question_id %>
</p>

<p>
  <strong>Option:</strong>
  <%= @multiple_choice_option.option %>
</p>

<%= link_to 'Edit', edit_multiple_choice_option_path(@multiple_choice_option) %> |
<%= link_to 'Back', multiple_choice_options_path %>